version: "3"

services: 
    app:
        container_name: app
        build: 
            context: .
        ports: 
            - "5000:5000"
        volumes: 
            - ./app:/app
        command: >
            sh -c "flask make &&
                    flask migrate &&
                    flask run --host 0.0.0.0"
        environment: 
            - DATABASE_HOST=db
            - DATABASE_NAME=app
            - TEST_DATABASE_NAME=tests
            - DATABASE_PORT=3306
            - DATABASE_USER=${DB_ADMIN_USER}
            - DATABASE_PASSWORD=${DB_ADMIN_PWD}
        depends_on: 
            - db
    db:
        container_name: database
        image: mysql:8
        restart: always
        environment:
            MYSQL_USER: ${DB_ADMIN_USER}
            MYSQL_PASSWORD: ${DB_ADMIN_PWD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
        volumes:
               - ./db_data:/var/lib/mysql
               - ./initdb:/docker-entrypoint-initdb.d
        ports:
            - "3306"
