name: Flask Application
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test-with-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker-compose up -d
        env:
          DB_ADMIN_USER: "Admin"
          DB_ADMIN_PWD: ${{ secrets.DB_ADMIN_PWD }}
          DB_ROOT_PWD: ${{ secrets.DB_ROOT_PWD }}
      - name: Run tests
        run: docker exec -it app sh -c "flask test"
